testing restaurantController w. reviews
isaac-fisher/we-eat pull request #2
Opened 2017-12-12 07:33 UTC by isaac-fisher

2017-12-12 13:14 UTC, liatperl requested changes

2017-12-12 13:14 UTC, liatperl commented on spec/factories/reviews.rb
> +
the review should have a reviewer property or name property if you defined this property as mandatory in the review model

2017-12-12 13:14 UTC, liatperl commented on spec/factories/restaurants.rb
> +  factory :restaurant do
Please try to write several tests that validate the model properties. For instance, check that the model is not valid if some of its mandatory properties are missing and that only when a value conform to a certain range the produced model is valid.

2017-12-12 13:14 UTC, liatperl commented on spec/factories/restaurants.rb
> +        evaluator.ratings.each{ |r| create(:review, restaurant: restaurant, rating: r)}
great 👍

2017-12-13 12:25 UTC, isaac-fisher commented
UPDATED

2017-12-13 13:45 UTC, liatperl approved these changes

2017-12-13 13:45 UTC, liatperl commented on spec/models/Restaurant_spec.rb
> +  it { should allow_values('35').for(:delivery_time) }
Delivery time should be an integer in the range of 1 to 1440.'35' and '5000' doesn't meet this criteria, the test should have failed.

2017-12-13 13:45 UTC, liatperl commented on spec/models/Restaurant_spec.rb
> +  it { should allow_values('35').for(:delivery_time) }
Maybe if you defined the delivery time as numericality: { only_integer: true } in the model the test would have failed, you can try that

2017-12-13 13:45 UTC, liatperl commented on spec/models/Restaurant_spec.rb
> +
can you also test the associations in the model? I think this is a good practice

2017-12-26 07:35 UTC, merged